import { mkdir, writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import ts from 'typescript';
import app from '../server/src/index';
import { openApiDocumentConfig } from '../server/src/api/openapi';

const outputUrl = new URL('../client/src/api/generated/types.d.ts', import.meta.url);

const document = app.getOpenAPIDocument(openApiDocumentConfig);
const ast = await openapiTS(document, {
    rootTypes: true,
    rootTypesNoSchemaPrefix: true,
    inject: "import '@bkper/bkper-api-types';",
    transform: schema => {
        const typescriptType = schema['x-typescript-type'];
        if (typeof typescriptType === 'string') {
            return ts.factory.createTypeReferenceNode(typescriptType);
        }
        return undefined;
    },
});
const contents = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

${astToString(ast)}`;

await mkdir(new URL('.', outputUrl), { recursive: true });
await writeFile(outputUrl, contents);

console.log(`Generated ${outputUrl.pathname}`);
